-- ============================================================================
-- HYPERMARKET STORE — PHASE 1 DATABASE SCHEMA (FROZEN)
-- ============================================================================
-- Scope (Phase 1 only):
--   categories, brands, products, product_variants, product_codes,
--   inventory, inventory_movements, product_price_history
-- Out of scope (do NOT add here without Phase 2 approval):
--   users/customers, cart, orders/order_items, payments, delivery, replacements
--
-- Target engine : PostgreSQL 15+ (uses CHECK, partial indexes, GENERATED
--                 columns, triggers — all available since PG 12).
-- PK strategy   : UUIDv7 GENERATED BY THE APPLICATION. Every INSERT
--                 (app code AND seed files) MUST send an application-side
--                 UUIDv7 as id. Column DEFAULTs are gen_random_uuid()
--                 (pgcrypto, ships with PG 15+) as a BACKSTOP ONLY for
--                 ad-hoc/ops inserts — never the normal path.
--                 Why not DEFAULT uuidv7()? That builtin exists ONLY in
--                 PG 18+; using it would make this file FAIL on PG 15-17
--                 with "function uuidv7() does not exist" at CREATE TABLE.
--                 Every major stack has a UUIDv7 library (pick one when the
--                 backend is chosen). When the whole fleet is PG 18+, the
--                 DEFAULTs may switch to uuidv7() with zero data migration.
-- Money         : NUMERIC(10,2)  — never FLOAT/REAL for money.
-- Quantities    : NUMERIC(12,3)  — gram precision for weight products.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- REVIEW-10: gen_random_uuid() backstop

-- ============================ HELPERS =======================================

-- Auto-maintain updated_at on every UPDATE.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Prevent circular category hierarchies (parent chain may never loop back).
-- A plain CHECK cannot do this; a trigger with a recursive CTE can.
CREATE OR REPLACE FUNCTION prevent_category_cycle()
RETURNS TRIGGER AS $$
DECLARE
  v_depth INT := 0;
BEGIN
  IF NEW.parent_id IS NULL THEN
    RETURN NEW;
  END IF;
  IF NEW.parent_id = NEW.id THEN
    RAISE EXCEPTION 'Category cannot be its own parent (%)', NEW.id;
  END IF;
  WITH RECURSIVE ancestors(id, parent_id, depth) AS (
    SELECT c.id, c.parent_id, 1
      FROM categories c
     WHERE c.id = NEW.parent_id
    UNION ALL
    SELECT c.id, c.parent_id, a.depth + 1
      FROM categories c
      JOIN ancestors a ON a.parent_id = c.id
     WHERE a.depth < 50
  )
  SELECT count(*) INTO v_depth FROM ancestors WHERE id = NEW.id;
  IF v_depth > 0 THEN
    RAISE EXCEPTION 'Circular category hierarchy detected for %', NEW.id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================ CATEGORIES ====================================

CREATE TABLE categories (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        VARCHAR(120) NOT NULL,
  slug        VARCHAR(140) NOT NULL UNIQUE,
  description TEXT NULL,
  image       VARCHAR(500) NULL,
  parent_id   UUID NULL REFERENCES categories (id)
                ON DELETE RESTRICT
                ON UPDATE CASCADE,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order  INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at  TIMESTAMPTZ NULL,                       -- soft delete
  CONSTRAINT chk_categories_slug_format CHECK (
    slug <> '' AND slug = lower(slug) AND position(' ' IN slug) = 0
  ),
  CONSTRAINT chk_categories_deleted_consistency CHECK (
    deleted_at IS NULL OR is_active = FALSE   -- deleted rows stay hidden
  )
);
CREATE INDEX idx_categories_parent_id  ON categories (parent_id);
-- REVIEW-12: no standalone (sort_order) index — sibling ordering is served by
-- idx_categories_storefront below; a global order-by-sort_order scan is not a
-- real query and the table is tiny/admin-rare.
CREATE INDEX idx_categories_storefront  ON categories (parent_id, sort_order)
  WHERE is_active AND deleted_at IS NULL;

-- ============================== BRANDS ======================================

CREATE TABLE brands (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       VARCHAR(120) NOT NULL,
  slug       VARCHAR(140) NOT NULL UNIQUE,
  logo       VARCHAR(500) NULL,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ NULL,
  CONSTRAINT chk_brands_slug_format CHECK (
    slug <> '' AND slug = lower(slug) AND position(' ' IN slug) = 0
  ),
  CONSTRAINT chk_brands_deleted_consistency CHECK (
    deleted_at IS NULL OR is_active = FALSE
  )
);

-- ============================= PRODUCTS =====================================

CREATE TABLE products (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name            VARCHAR(160) NOT NULL,
  slug            VARCHAR(180) NOT NULL UNIQUE,
  description     TEXT NULL,
  category_id     UUID NOT NULL REFERENCES categories (id)
                    ON DELETE RESTRICT
                    ON UPDATE CASCADE,
  brand_id        UUID NULL REFERENCES brands (id)
                    ON DELETE RESTRICT
                    ON UPDATE CASCADE,
  product_type    VARCHAR(10) NOT NULL
                    CONSTRAINT chk_products_type CHECK (product_type IN ('PIECE', 'WEIGHT')),
  unit            VARCHAR(10) NOT NULL
                    CONSTRAINT chk_products_unit CHECK (unit IN ('PIECE', 'KG', 'GRAM', 'LITER', 'ML')),
  sale_step_grams INTEGER NULL,   -- canonical step; NULL for PIECE products
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,    -- admin visibility switch
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at      TIMESTAMPTZ NULL,                 -- soft delete, never hard-delete
  -- WEIGHT products: metric weight unit + mandatory positive step.
  -- PIECE products: no sale step allowed (prevents silent misuse).
  CONSTRAINT chk_products_weight_rule CHECK (
    (product_type = 'WEIGHT' AND unit IN ('KG', 'GRAM')
       AND sale_step_grams IS NOT NULL AND sale_step_grams > 0)
    OR
    (product_type = 'PIECE' AND unit = 'PIECE' AND sale_step_grams IS NULL)
  ),
  CONSTRAINT chk_products_slug_format CHECK (
    slug <> '' AND slug = lower(slug) AND position(' ' IN slug) = 0
  ),
  -- REVIEW-02: NO is_available column (removed). Product-level availability is
  -- derived live via the product_stock_status VIEW (see below) — a stored copy
  -- would drift from inventory and serialize concurrent sales on one product row.
  CONSTRAINT chk_products_deleted_consistency CHECK (
    deleted_at IS NULL OR is_active = FALSE
  )
);
CREATE INDEX idx_products_category_id ON products (category_id);
CREATE INDEX idx_products_brand_id    ON products (brand_id);
CREATE INDEX idx_products_type        ON products (product_type);
-- Main storefront listing: active, not deleted, per category.
CREATE INDEX idx_products_storefront  ON products (category_id, is_active)
  WHERE deleted_at IS NULL;

-- ========================== PRODUCT VARIANTS ================================
-- Price lives HERE (never on products). One row per sellable size.
-- Weight products normally have exactly ONE loose-weight variant
-- (e.g. "KG"): customer weight options (125g/250g/...) are derived in the
-- app from products.sale_step_grams, NOT stored as extra variants.

CREATE TABLE product_variants (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id       UUID NOT NULL REFERENCES products (id)
                     ON DELETE RESTRICT
                     ON UPDATE CASCADE,
  name             VARCHAR(120) NOT NULL,             -- e.g. '330 ML', 'KG'
  size_value       NUMERIC(10,3) NULL CHECK (size_value IS NULL OR size_value > 0),
  size_unit        VARCHAR(10) NULL
                     CONSTRAINT chk_variants_size_unit
                     CHECK (size_unit IS NULL OR size_unit IN ('PIECE','KG','GRAM','LITER','ML')),
  price            NUMERIC(10,2) NOT NULL CHECK (price >= 0),
  compare_at_price NUMERIC(10,2) NULL CHECK (compare_at_price IS NULL OR compare_at_price >= 0),
  cost_price       NUMERIC(10,2) NULL CHECK (cost_price IS NULL OR cost_price >= 0),
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at       TIMESTAMPTZ NULL,
  CONSTRAINT uq_variants_product_name UNIQUE (product_id, name),
  -- "Was price" must be a real discount anchor, not a lower number.
  CONSTRAINT chk_variants_compare_price CHECK (
    compare_at_price IS NULL OR compare_at_price >= price
  ),
  CONSTRAINT chk_variants_deleted_consistency CHECK (
    deleted_at IS NULL OR is_active = FALSE
  )
);
CREATE INDEX idx_variants_product_id ON product_variants (product_id);
CREATE INDEX idx_variants_sellable    ON product_variants (product_id)
  WHERE is_active AND deleted_at IS NULL;

-- ========================== PRODUCT CODES ===================================
-- code is VARCHAR on purpose: preserves leading zeros ('02010106').
-- Global UNIQUE: a cashier scan must resolve to EXACTLY one variant.

CREATE TABLE product_codes (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_variant_id UUID NOT NULL REFERENCES product_variants (id)
                       ON DELETE CASCADE        -- codes have no independent history;
                       ON UPDATE CASCADE,       -- only table with CASCADE (see doc §F)
  code              VARCHAR(64) NOT NULL UNIQUE,
  type              VARCHAR(20) NOT NULL
                      CONSTRAINT chk_codes_type CHECK (type IN ('BARCODE', 'INTERNAL_CODE')),
  is_primary        BOOLEAN NOT NULL DEFAULT FALSE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_codes_code_format CHECK (code <> '' AND position(' ' IN code) = 0)
);
CREATE INDEX idx_codes_variant_id ON product_codes (product_variant_id);
-- Business rule: at most ONE primary code per variant.
CREATE UNIQUE INDEX uq_codes_one_primary
  ON product_codes (product_variant_id) WHERE is_primary;

-- ============================= INVENTORY ====================================
-- One row per variant (created together with the variant in one transaction).
-- available_quantity is a GENERATED column: impossible to drift out of sync.
-- Units: PIECE variants store whole numbers (e.g. 500.000);
--        WEIGHT variants store KG with gram precision (e.g. 47.350).

CREATE TABLE inventory (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_variant_id UUID NOT NULL UNIQUE REFERENCES product_variants (id)
                       ON DELETE RESTRICT
                       ON UPDATE CASCADE,
  quantity           NUMERIC(12,3) NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  reserved_quantity  NUMERIC(12,3) NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
  available_quantity NUMERIC(12,3)
                       GENERATED ALWAYS AS (quantity - reserved_quantity) STORED,
  low_stock_threshold NUMERIC(12,3) NULL CHECK (low_stock_threshold IS NULL OR low_stock_threshold >= 0),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_inventory_reserved_lte_quantity CHECK (reserved_quantity <= quantity)
  -- available_quantity >= 0 follows automatically from the two checks above.
);

-- ========================= INVENTORY MOVEMENTS ===============================
-- Append-only audit log. Every stock change MUST insert exactly one row here
-- in the SAME transaction as the inventory UPDATE (enforced by convention +
-- code review in Phase 1; FK to orders added in Phase 2).

CREATE TABLE inventory_movements (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_variant_id UUID NOT NULL REFERENCES product_variants (id)
                       ON DELETE RESTRICT
                       ON UPDATE CASCADE,
  movement_type      VARCHAR(20) NOT NULL CONSTRAINT chk_movements_type CHECK (
                       movement_type IN ('STOCK_IN','SALE','RETURN','WASTE',
                                         'ADJUSTMENT','REPLACEMENT','CANCELLED_ORDER')
                     ),
  quantity           NUMERIC(12,3) NOT NULL CONSTRAINT chk_movements_qty_nonzero CHECK (quantity <> 0),
  previous_quantity  NUMERIC(12,3) NOT NULL CHECK (previous_quantity >= 0),
  new_quantity       NUMERIC(12,3) NOT NULL CHECK (new_quantity >= 0),
  reference_type     VARCHAR(20) NULL CONSTRAINT chk_movements_ref_type CHECK (
                       reference_type IS NULL OR reference_type IN
                       ('ORDER','PURCHASE','RETURN','ADJUSTMENT','MANUAL')
                     ),
  reference_id       VARCHAR(64) NULL,   -- VARCHAR: holds UUID strings today,
                                         -- external doc numbers tomorrow
  reason             TEXT NULL,
  created_by         UUID NULL,          -- FK -> users(id) to be added in Phase 2
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- The log row must arithmetically agree with itself.
  CONSTRAINT chk_movements_math CHECK (new_quantity = previous_quantity + quantity),
  -- A reference id is meaningless without its type.
  CONSTRAINT chk_movements_ref_pair CHECK (
    reference_id IS NULL OR reference_type IS NOT NULL
  )
  -- Immutable by convention: NO updated_at / deleted_at. Grant only INSERT+SELECT
  -- on this table to the application role (no UPDATE/DELETE).
);
CREATE INDEX idx_movements_variant_time ON inventory_movements (product_variant_id, created_at DESC);
CREATE INDEX idx_movements_type         ON inventory_movements (movement_type);
CREATE INDEX idx_movements_reference   ON inventory_movements (reference_type, reference_id);

-- ========================== PRICE HISTORY ====================================
-- Append-only. Changing product_variants.price MUST insert one row here in the
-- same transaction. Old orders NEVER read this table (Phase 2 order_items
-- stores unit_price_snapshot); carts re-price from the live variant price.

CREATE TABLE product_price_history (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_variant_id UUID NOT NULL REFERENCES product_variants (id)
                       ON DELETE RESTRICT
                       ON UPDATE CASCADE,
  old_price          NUMERIC(10,2) NOT NULL CHECK (old_price >= 0),
  new_price          NUMERIC(10,2) NOT NULL CHECK (new_price >= 0),
  changed_by         UUID NULL,          -- FK -> users(id) to be added in Phase 2
  reason             TEXT NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_price_history_changed CHECK (old_price <> new_price)
  -- Immutable by convention: NO updated_at / deleted_at.
);
CREATE INDEX idx_price_history_variant_time
  ON product_price_history (product_variant_id, created_at DESC);

-- ====================== DERIVED READ SUPPORT ================================
-- REVIEW-02: product-level availability is DERIVED, never stored. A single
-- stored boolean per product cannot represent mixed per-variant stock, and any
-- stored copy would drift from inventory (extra writer in every stock tx) and
-- serialize concurrent sales of sibling variants on one product row.
-- This view is the ONE definition of "product in stock".
-- Variant-level truth always stays in inventory.available_quantity.
-- NOTE: deliberately NO SUM of quantities here — variants of one product may
-- use different units (ML vs LITER), so a summed total would be unit-incoherent.

CREATE OR REPLACE VIEW product_stock_status AS
SELECT
  p.id AS product_id,
  COUNT(v.id) FILTER (
    WHERE v.is_active AND v.deleted_at IS NULL) AS sellable_variants,
  COUNT(v.id) FILTER (
    WHERE v.is_active AND v.deleted_at IS NULL
      AND i.available_quantity > 0) AS in_stock_variants,
  EXISTS (SELECT 1
            FROM product_variants v2
            JOIN inventory i2 ON i2.product_variant_id = v2.id
           WHERE v2.product_id = p.id
             AND v2.is_active AND v2.deleted_at IS NULL
             AND i2.available_quantity > 0) AS is_in_stock
FROM products p
LEFT JOIN product_variants v ON v.product_id = p.id
LEFT JOIN inventory i ON i.product_variant_id = v.id
GROUP BY p.id;

-- Frozen cross-table contracts (enforced by convention + review; the DB cannot
-- express "exactly one log row per UPDATE" without fragile machinery, so these
-- COMMENTs keep the rule attached to the objects themselves).
COMMENT ON TABLE inventory IS
  'Current stock per variant (1:1). Every UPDATE MUST be paired with exactly one '
  'inventory_movements row in the SAME transaction (frozen pattern, see arch doc §A).';
COMMENT ON TABLE inventory_movements IS
  'Append-only stock audit. Self-checked by chk_movements_math '
  '(new = previous + quantity). previous_quantity MUST come from the locked '
  'inventory row (SELECT FOR UPDATE ... RETURNING), never from app memory.';
COMMENT ON TABLE product_price_history IS
  'Append-only price audit. NEVER a pricing source for old orders: Phase 2 '
  'order_items must snapshot unit_price (+ pricing unit) at order time.';
COMMENT ON COLUMN products.sale_step_grams IS
  'REVIEW-01: canonical offer granularity in WHOLE grams, product-level. The UI '
  'derives weight options (step, 2*step, ...) from this single value; changing '
  '125 to 100/250/500 is one UPDATE, no DDL. Fractional-gram steps are out of '
  'scope for deli-scale retail (accepted limitation).';
COMMENT ON COLUMN product_variants.size_value IS
  'REVIEW-03: PRICE BASIS of this variant (e.g. 1 per KG, 330 per ML). Never a '
  'customer requested/actual weight — those are order-time facts living in '
  'Phase 2 order_items only.';
COMMENT ON COLUMN product_variants.size_unit IS
  'REVIEW-03: unit of the price basis above. Pairs with size_value; both describe '
  'how price is quoted, not what the customer asked to be weighed.';

-- ============================== TRIGGERS =====================================

CREATE TRIGGER trg_categories_updated_at
  BEFORE UPDATE ON categories FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_categories_no_cycle
  BEFORE INSERT OR UPDATE OF parent_id ON categories
  FOR EACH ROW EXECUTE FUNCTION prevent_category_cycle();

CREATE TRIGGER trg_brands_updated_at
  BEFORE UPDATE ON brands FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_products_updated_at
  BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_variants_updated_at
  BEFORE UPDATE ON product_variants FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_codes_updated_at
  BEFORE UPDATE ON product_codes FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- NOTE: inventory has no created_at (it is a current-state row, not an event);
-- updated_at is maintained by the trigger below.
CREATE TRIGGER trg_inventory_updated_at
  BEFORE UPDATE ON inventory FOR EACH ROW EXECUTE FUNCTION set_updated_at();
